require "finbar.plugins"
require "finbar.options"
require "finbar.keymaps"
require "finbar.colorscheme"
require "finbar.cmp"
require "finbar.lsp"
require "finbar.treesitter"
require "finbar.telescope"
require "finbar.autopairs"
require "finbar.gitsigns"
require "finbar.comment"
require "finbar.nvim-tree"
require "finbar.which-key"
require "finbar.barbar"
require "finbar.toggleterm"
require "finbar.lualine"
require "finbar.alpha"
require "finbar.project"
require "finbar.dap"
require "finbar.illuminate"
require "finbar.diffview"
require "finbar.harpoon"
--[[ require "finbar.marks" ]]
--[[ require "finbar.nvim-metals" ]]
